Bunsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('gamelog.urls')),
    url(r'^admin/', admin.site.urls),
]

gamelog/urls.py
from django.conf.urls import url

from . import views

app_name = 'gamelog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^gamelog/$', views.GameLogView.as_view(), name='gamelog'),
    url(r'^gamelog/(?P<pk>[0-9]+)/$', views.GameView.as_view(), name='game'),
    url(r'^gamelog/add/$', views.add_game, name='add_game'),
    url(r'^gamelog/get_player_decks/(?P<player_id>[0-9]+)/$', views.get_player_decks, name='get_player_decks'),
    url(r'^stats/$', views.StatsView.as_view(), name='stats'),
    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
]

gamelog/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone


class Format(models.Model):
    name = models.CharField(max_length=20)
    
    def __str__(self):
        return self.name
    

class Player(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    
    created_date = models.DateTimeField(editable=False, default=timezone.now())
    updated_date = models.DateTimeField(editable=False)

    def save(self):
        self.updated_date = timezone.now()
        return super(Player, self).save()

    def __str__(self):
        return self.first_name + ' ' + self.last_name


class Deck(models.Model):
    name = models.CharField(max_length=50)
    format = models.ForeignKey(Format)
    web_link = models.CharField(max_length=100)
    player = models.ForeignKey(Player, null=True)
    
    def __str__(self):
        return self.format.name + ": " + self.name
    
    
class Location(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name
   

class Game(models.Model):
    players = models.ManyToManyField(Player, related_name='players')
    location = models.ForeignKey(Location)
    format = models.ForeignKey(Format)
    created_date = models.DateTimeField(editable=False, default=timezone.now())
    updated_date = models.DateTimeField(editable=False)
    winner = models.ForeignKey(Player, related_name='winner', null=True)
    
    def save(self):
        self.updated_date = timezone.now()
        return super(Game, self).save()

gamelog/forms.py
from django import forms
from gamelog.models import Format, Location, Player


class GameForm(forms.Form):
    format = forms.ModelChoiceField(queryset=Format.objects.all(),
                                    empty_label='--Select Format--',
                                    required=True, label='Format:')
    location = forms.ModelChoiceField(queryset=Location.objects.all(),
                                      empty_label='--Select Location--',
                                      required=True, label='Location:')
    players = forms.ModelChoiceField(queryset=Player.objects.all(),
                                     empty_label='--Select Player--')
    player_count = forms.CharField(widget=forms.HiddenInput())

    def __init__(self, *args, **kwargs):
        player = kwargs.pop('player', 0)
        super(GameForm, self).__init__(*args, **kwargs)

        self.fields['player_count'].initial = player
        for i in range(int(player)):
            self.fields['player_{i}'.format(i=i)] = forms.CharField()

gamelog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core.urlresolvers import reverse
from django.views import generic
from .models import Game, Location, Format, Player, Deck
import forms


class IndexView(generic.TemplateView):
    template_name = 'gamelog/home.html'


class GameLogView(generic.ListView):
    template_name = 'gamelog/gamelog.html'
    context_object_name = 'gamelog_list'
    queryset = Game.objects.all()

    def get_context_data(self, **kwargs):
        context = super(GameLogView, self).get_context_data(**kwargs)
        context['Locations'] = Location.objects.all()
        context['Formats'] = Format.objects.all()
        context['Players'] = Player.objects.all()
        # context['Decks'] = Deck.objects.all()
        # context['form'] = forms.GameForm()
        return context


class GameView(generic.DetailView):
    model = Game
    template_name = 'gamelog/game.html'

    def get_context_data(self, **kwargs):
        context = super(GameView, self).get_context_data(**kwargs)
        p = Game.objects.get(pk=self.kwargs['pk']).players
        player_ids = p.values_list('id', flat=True)
        context['decks'] = Deck.objects.filter(player_id__in=player_ids)
        return context


class StatsView(generic.TemplateView):
    template_name = 'gamelog/stats.html'


class ProfileView(generic.TemplateView):
    template_name = 'gamelog/profile.html'


def get_player_decks(request, player_id):
    if request.is_ajax():
        decks = Deck.objects.filter(player_id=player_id)
        response_data = []
        for deck in decks:
            data = {}
            data['id'] = deck.id
            data['name'] = deck.name
            data['format'] = deck.format.name
            response_data.append(data)

        return JsonResponse(response_data, safe=False)


def add_game(request):
    # Get players
    
    # Get decks

    # Get location
    location_id = request.POST['location']
    l = Location.objects.get(pk=location_id)

    # Get format
    format_id = request.POST['format']
    f = Format.objects.get(pk=format_id)

    # Create game object
    g = Game(location=l, format=f)

    # Save it
    g.save()

    # Show results
    return HttpResponseRedirect(reverse('gamelog:game', args=(g.id,)))

gamelog/templates/gamelog/game.html
<!DOCTYPE html>
<html lang="en">
{%  include 'gamelog/head.html' %}
<body>
<div id="wrapper">
    {% include 'gamelog/header.html' %}
    <div id="bodybox">
        <div id="gamelogbox">
            <h1>{{ game.format }} at {{ game.location }}</h1>
            <h2>Winner: {{ game.winner }}</h2>
            Players:
            <ul>
            {% for player in game.players.all %}
                <li>{{ player }} playing</li>
            {% endfor %}
            </ul>
        {{ decks }}
        </div>
    </div>
</div>
</body>
</html>

gamelog/templates/gamelog/gamelog.html
<!DOCTYPE html>
<html>
    {%  include 'gamelog/head.html' %}
	
	<body>
		<div id="wrapper">
			{% include 'gamelog/header.html' %}
			<div id="bodybox">
				<div id="gamelogbox">

                    {% if gamelog_list %}
                        <ol>
                        {% for game in gamelog_list %}
                            <li><a href="{% url 'gamelog:game' game.id %}">{{ game.format }} at {{ game.location }}</a></li>
                        {% endfor %}
                        </ol>
                    {% endif %}
                    <form action="{% url 'gamelog:add_game' %}" method="post">
                        {% csrf_token %}
                        <br>
                        Format:<br/>
                        <select name="format">
                        {% if Formats %}
                            {% for format in Formats %}
                                <option value="{{ format.id }}">{{ format.name }}</option>
                            {% endfor %}
                        {% endif %}
                        </select><br><br>

                        Location:<br/>
                        <select name="location">
                        {% if Locations %}
                            {% for location in Locations %}
                                <option value="{{ location.id }}">{{ location.name }}</option>
                            {% endfor %}
                        {% endif %}
                        </select>
                        <br><br>

                        Player:<br/>
                        <select name="ddlPlayer" id="ddlPlayer">
                        <option value="-1">--Select Player--</option>
                        {% if Players %}
                            {% for player in Players %}
                                <option value="{{ player.id }}">{{ player.first_name }} {{ player.last_name }}</option>
                            {% endfor %}
                        {% endif %}
                        <option value="0">--ADD NEW PLAYER--</option>
                        </select>

                        <div id="deck" style="display: none;">
                            Deck:<br/>
                            <select name="ddlDeck" id="ddlDeck">
                                <option value="-1">--Select Deck--</option>
                            </select>
                        </div>

                        <div id="addPlayerBox" style="display: none;">
                            First Name:<input type="text" name="player" id="player">
                        </div>

                        <input type="button" value="Add" id="addPlayer">
                        <div id="playerbox">
                            <table style="width:100%" align="center" id="players">
                                <thead>
                                    <tr>
                                        <th>Player</th>
                                        <th>Deck</th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </div>
                        <br><br>

                        <a href="home.html"><input type="submit" value="Submit"></a>
                        <br>
                    </div>
                </form>
				
			</div>
			<div id="footer">
			</div>
		</div>
	
	</body>
    <script type="text/javascript">
        $(document).ready(function() {
            $("#ddlPlayer").change(function() {
                if ($(this).val() == 0){
                    $("#addPlayerBox").show();
                } else {
                    $("#addPlayerBox").hide();

                    $("#ddlDeck").find("option").remove();

                    if ($("#ddlPlayer option:selected").val() <= 0){
                        $("#deck").hide();
                        return;
                    }

                    //show deck picker
                    $("#deck").show();

                    $.ajax({
                        url: "get_player_decks/" + $("#ddlPlayer option:selected").val() + "/",
                        type: "GET",
                        success: function(data) {
                            //console.log(data);
                            $.each(data, function(key, value){
                                $("#ddlDeck")
                                        .append($("<option></option>")
                                        .attr("value", value.id)
                                        .text(value.format + ": " + value.name));
                            });

                        },
                        error: function(data){
                            console.log("ERROR: " + data);
                        }
                    })
                }
            });

            $("#addPlayer").click(function() {
                var selectedText = $("#ddlPlayer :selected").text();
                var selectedVal = $("#ddlPlayer").val();
                $("#players tbody").append("<tr><td>" + selectedText + "</td></tr>");
            })


        });
    </script>

</html>

gamelog/templates/gamelog/gametracker.html
<!html>
<html>
	<head>
		<link rel="stylesheet" type="text/css" href="style.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
		<script src="script.js"></script>
	</head>
	
	<body>
		<div id="wrapper">
			<div id="header">
				<div class="nav">
					<a href="home.html"><div class="navbox">Home</div></a>
					<a href="gamelog.html"><div class="navbox">Log Game</div></a>
					<a href="stats.html"><div class="navbox">Stats</div></a>
					<a href="profile.html"><div class="navbox">Profile</div></a>
				</div>
			</div>
			<div id="bodybox">
				<div id="gamelogbox">
					<div id="playerbox">
						<table style="width:100%" align="center" id="Game State">
  							<tr>
    							<th>Format</th>
    							<th>Location</th>
  							</tr>
						</table>
						<br>
						<table style="width:100%" align="center" id="players">
							<tr>
								<th>Player</th>
								<th>Deck</th>
								<th>Winner</th>
							</tr>
						</table>
						<br>
						<h1>*</h1>
						<br>
						<textarea name="asterix" id="aterix" cols="25" rows="5">
						</textarea>

					</div>
				</div>
				
			</div>
			<div id="footer">
			</div>
		</div>
	
	</body>

</html>

gamelog/templates/gamelog/head.html
<head>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'script.js' %}"></script>
    <title></title>
</head>

gamelog/templates/gamelog/header.html
<div id="header">
    <div class="nav">
        <a href="{% url 'gamelog:index' %}"><div class="navbox">Home</div></a>
        <a href="{% url 'gamelog:gamelog' %}"><div class="navbox">Log Game</div></a>
        <a href="{% url 'gamelog:stats' %}"><div class="navbox">Stats</div></a>
        <a href="{% url 'gamelog:profile' %}"><div class="navbox">Profile</div></a>
    </div>
</div>

gamelog/templates/gamelog/home.html
<!html>
<html>
	{%  include 'gamelog/head.html' %}
	
	<body>
		<div id="wrapper">
            {% include 'gamelog/header.html' %}
			<div id="bodybox">
				<div id="leftcolumn">News</div>
				<div id="rightcolumn">Recent Games</div>
				
			</div>
			<div id="footer">
			</div>
		</div>
	
	</body>

</html>

gamelog/templates/gamelog/profile.html
<!html>
<html>
	{%  include 'gamelog/head.html' %}
	
	<body>
		<div id="wrapper">
			{% include 'gamelog/header.html' %}
			<div id="bodybox">
				<div id="leftcolumn">Zach</div>
				<div id="rightcolumn">Recent Games</div>
				
			</div>
			<div id="footer">
			</div>
		</div>
	
	</body>

</html>

gamelog/templates/gamelog/stats.html
<!html>
<html>
	{%  include 'gamelog/head.html' %}
	
	<body>
		<div id="wrapper">
			{% include 'gamelog/header.html' %}
			<div id="bodybox">
				<div id="leftcolumn">Stats</div>
				<div id="rightcolumn">Recent Games</div>
				
			</div>
			<div id="footer">
			</div>
		</div>
	
	</body>

</html>